# version: '3.8'

services:

  postgres:
    image: 'postgres:16.2'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5464:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # copy the sql script to create tables
      # - ./sql/create_tables_v3.sql:/docker-entrypoint-initdb.d/create_tables.sql
    restart: unless-stopped



  minio:
    image: minio/minio:RELEASE.2024-06-06T09-36-42Z
    ports:
      - "9096:9000"
      - "9097:9001"
    restart: unless-stopped
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin2024
    command: server --console-address ":9001" /data

volumes:
  postgres_data:
  minio_storage: {}